### ISSUE TITLE
Default toggle?

### ISSUE THREAD

**Issue by tobyl** [yelouafi/redux-saga-devtool#11]
Hey.. I might be missing something really simple here, but is there a way to set the toggle to be closed by default? Currently have to close it each time..

Thanks!

**Comment by Andarist** [comment]
could probably be stored in `localStorage` or smth and retrieved upon refresh

**Comment by salvoravida** [comment]
https://github.com/redux-saga/redux-saga-devtools/pull/12

**Comment by yihou** [comment]
can anyone update this changes to npm?

**Comment by Andarist** [comment]
@yihou I've published 0.2.0 just now, enjoy

**Comment by yihou** [comment]
@Andarist thanks a bunch!
