### ISSUE TITLE
Typo 'unkown' should be 'unknown'

### ISSUE THREAD

**Issue by TAGC** [yelouafi/redux-saga-devtool#14]
I've just started using this devtool and I've noticed it uses 'unkown' in places where I believe you want 'unknown'.

**Comment by TAGC** [comment]
There's another instance of this typo I've found [here](https://github.com/redux-saga/redux-saga-devtools/blob/cef3e58487369bb173def8fa745514bcc8db351f/src/containers/SagaMonitorView/SagaMonitorView.js) in `renderCurrentView`.

**Comment by yelouafi** [comment]
fixed by https://github.com/redux-saga/redux-saga-devtools/commit/a56274cab7d473f00440ec724b7329aa9fed2c87
